# project
### 모든 프로젝트 조회
GET http://localhost:8080/projects

### 해당 프로젝트 조회

GET http://localhost:8080/projects/1

###

POST http://localhost:8080/projects/goback10000
Content-Type: application/json

{
  "title": "test11",
  "content" : "test-project"
}

###

PATCH http://localhost:8080/projects/3
Content-Type: application/json

{
  "title": "*** test ***",
  "content" : "test-project"
}

###

DELETE http://localhost:8080/projects/3

###


# project-member
GET http://localhost:8080/projects/2/accounts

###


GET http://localhost:8080/projects/2/accounts/goback10000


###
GET http://localhost:8080/projects/accounts/goback10000


###
POST http://localhost:8080/projects/2/accounts/goback10000
Content-Type: application/json

{
    "id" : 3,
  "members" : [
    {
      "id" :"test1"
    },
    {
      "id" : "test2"
    },
    {
      "id": "test3"
    }
  ]
}

###
POST http://localhost:8080/projects/2/accounts/goback10000
Content-Type: application/json

{
  "id" : 2,
  "members" : [
    {
      "id" :"test1"
    }
  ]
}

###
DELETE http://localhost:8080/projects/2/accounts/minidooray

###

# tag
GET http://localhost:8080/projects/1/tags


###
GET http://localhost:8080/projects/1/tasks/tags/1


###
POST http://localhost:8080/projects/1/tags
Content-Type: application/json

{
  "name" : "tag-test-create"
}

###
PATCH http://localhost:8080/projects/1/tags/7
Content-Type: application/json

{
  "name" : "tag-test-update"
}

###
DELETE http://localhost:8080/projects/1/tags/7


###
# milestone
GET http://localhost:8080/projects/1/milestones

### 1번 마일스톤이 등록된 task 조회
GET http://localhost:8080/projects/1/tasks/milestones/1

###
GET http://localhost:8080/projects/1/milestones/1

###
POST http://localhost:8080/projects/1/milestones
Content-Type: application/json

{
  "name" : "test-milestone-create",
  "start" : "2023-06-10",
  "end" : "2023-06-16"
}

###
PATCH http://localhost:8080/projects/1/milestones/5
Content-Type: application/json

{
  "name" : "test-milestone-update",
  "start" : "2023-06-02",
  "end" : "2023-06-16"
}

###
DELETE http://localhost:8080/projects/1/milestones/1


###

# task

